Run the CI on all supported ruby versions
`solidus_bolt` needs to be disabled for the dummy app otherwise it
fails due to the contrived nature of the app.

For rubies < 3 using the latest rails we need to use the external
net/http gem to avoid this error:

rake aborted!
LoadError: cannot load such file -- net/smtp
/home/circleci/project/vendor/bundle/v3.1/ruby/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `require'
/home/circleci/project/vendor/bundle/v3.1/ruby/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/circleci/project/vendor/bundle/v3.1/ruby/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/circleci/project/vendor/bundle/v3.1/ruby/3.1.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `require'
/home/circleci/project/vendor/bundle/v3.1/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:9:in `<module:Mail>'
/home/circleci/project/vendor/bundle/v3.1/ruby/3.1.0/gems/mail-2.7.1/lib/mail.rb:3:in `<top (required)>'

Ref https://github.com/rails/rails/pull/44175#issuecomment-1023595691